---
# YAML documents begin with ---

# The minus in YAML this indicates a list item.  The playbook
# contains a list of plays, with each play being a dictionary
-

  # name of the
  name: MOTD play
  # Target: where our play will run and options it will run with
  hosts: linux
  user: user1
  # gather_facts: false -- need facts

  # Variable: variables that will apply to the play, on all target systems
  vars:
    motd_centos: "Welcome to CentOS Linux - Ansible Rocks\n"
    motd_ubuntu: "Welcome to Ubuntu Linux - Ansible Rocks\n"

  # Task: the list of tasks that will be executed within the play,
  # this section can also be used for pre and post tasks
  tasks:
    - name: Configure a MOTD (message of the day)
      copy:
        content: "{{ motd_centos }}"
        dest: /etc/motd
      notify: MOTD changed
      when: ansible_distribution == "CentOS"

    - name: Configure a MOTD (message of the day)
      copy:
        content: "{{ motd_ubuntu }}"
        dest: /etc/motd
      notify: MOTD changed
      when: ansible_distribution == "Ubuntu"
 
  # Handlers: handlers that are executed as a notify key from a task
  handlers:
    - name: MOTD changed
      debug:
        msg: The MOTD was changed

  # Roles: list of roles to be imported into the play

# Three dots indicate the end of a YAML document
...
