---
# first play for all prod servers
  - name: base system configuration for all linux servers
    hosts: prod
    become: true
    tasks:
      - name: create ansible user with uid 5006
        user:
          name: ansible
          state: present
          uid: 5006

      - name: remove user user2 if present
        user:
          name: user2
          state: absent

      - name: install vim
        package:
          name: vim
          state: present

      - name: install ntp
        package:
          name: ntp
          state: present

      - name: start ntp service on centos nodes
        service:
          name: ntpd
          state: started
        when: ansible_distribution=="CentOS"


      - name: start ntp service on ubuntu nodes
        service:
          name: ntp
          state: started
        when: ansible_distribution=="Ubuntu"

# second play to config app servers

  - name: config app servers
    hosts: app
    become: true
    gather_facts: false
    tasks:
      - name: install git
        package:
          name: git
          state: present

      - name: create geo user
        user:
          name: geo
          state: present
          uid: 5007
...
